### ISSUE TITLE
gentle error message, on runtime error

### ISSUE THREAD

**Issue by podhmo** [podhmo/kamidana#27]
refinement from #19

**Comment by podhmo** [comment]
Currently, a runtime error is treated as normal python exception.

zero.div.j2

```
# zero division error
{{ 1 / 0}}
```

```
Traceback (most recent call last):
  File "$HOME/venvs/my/bin/kamidana", line 12, in <module>
    sys.exit(main())
  File "$HOME/venvs/my/kamidana/kamidana/commands/onefile.py", line 60, in main
    driver.run(args.template, args.dst)
  File "$HOME/venvs/my/kamidana/kamidana/driver.py", line 61, in run
    result = self.transform(template)
  File "$HOME/venvs/my/kamidana/kamidana/driver.py", line 48, in transform
    return _render_with_newline(t, self.loader.data)
  File "$HOME/venvs/my/kamidana/kamidana/driver.py", line 16, in _render_with_newline
    r = t.render(**data)
  File "$HOME/venvs/my/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "$HOME/venvs/my/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "$HOME/venvs/my/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "$HOME/venvs/my/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
ZeroDivisionError: division by zero
```

**Comment by podhmo** [comment]
it is better.

```
exception: builtins.ZeroDivisionError
message: division by zero
where: 02include-ng/zero.div.j2
------------------------------------------------------------
02include-ng/zero.div.j2:
      1: # zero division error
  ->  2: {{1/0}}
```
